#version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  fast_apis:
    image: tenders-apis
    build:
      context: .
    container_name: tenders_apis_container
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo-container:27017

volumes:
  mongo_data:
