version: "3.8"
services:
  

  mongodb:
    image: mongo
    ports:
      - "27018:27018"
    networks:
      - my-network


  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - mongodb

networks:
  my-network:
    driver: bridge